### ISSUE TITLE
Ho do I listen to account events?

### ISSUE THREAD

**Issue by inartin** [randlabs/myalgo-connect#74]
How do I set up events for accounts disconnected/connected/error etc?

For example when the page reloads, how do I check if the account was already connected to my app? Do I need to run, connect, every time?
Or what if the user disconnected the app from his wallet?

I'm referring to similar events that there are on MetaMask and other web3 wallets.

**Comment by M-Picco** [comment]
Hi @inartin! Due to its design, MyAlgoConnect does not currently provide an event listener interface.

Alternatively, what you can do is ask the user to connect for the first time, store the connected account and assume the user is connected while this value is present. When the user decides to disconnect/logout, clear this value.

If the user disconnects the site through their wallet settings, they will get a "Site not connected message" through the popup. When they close it, the library will throw an exception and the returned promise will be rejected, so it should be treated as an error case from the application's point of view.

**Comment by inartin** [comment]
Thank you for your response and the suggested workaround @M-Picco 
We can use this method for now, but I hope some form of events will be added in future updates since this is one of the key features for a web3 wallet IMO.
